export const MESSAGES = {
  EMAIL_OR_PHONE_REQUIRED: 'Email or phone is required',
  INVALID_OTP: 'Invalid OTP',
  OTP_SESSION_EXPIRED: 'OTP session not found or expired',
  OTP_NOT_VERIFIED: 'OTP not verified',
  USERNAME_TAKEN: 'Username already taken',
  PROFILE_CREATED: 'Profile created successfully',
  OTP_SENT: 'OTP sent successfully',
  OTP_VERIFIED: 'OTP verified successfully',
  LOGIN_SUCCESS: 'Login successful',
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_ALREADY_EXISTS: 'User already exists',
  USER_NOT_FOUND: 'User not found',
  PASSWORD_MUST_BE_DIFFERENT: 'New password must be different from old password',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
  OTP_ALREADY_VERIFIED: 'OTP already verified',
};