export const AUTH_MESSAGES = {
  EMAIL_OR_PHONE_REQUIRED: 'Email or phone is required',
  INVALID_OTP: 'Invalid OTP',
  OTP_SESSION_EXPIRED: 'OTP session not found or expired',
  OTP_NOT_VERIFIED: 'OTP not verified',
  USERNAME_TAKEN: 'Username already taken',
  PROFILE_CREATED: 'Profile created successfully',
  OTP_SENT: 'OTP sent successfully',
  OTP_VERIFIED: 'OTP verified successfully',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  INVALID_CREDENTIALS: 'Invalid credentials',
  SESSION_EXPIRED: 'Session expired. Please login again',
  USER_ALREADY_EXISTS: 'User already exists',
  USER_NOT_FOUND: 'User not found',
  PASSWORD_MUST_BE_DIFFERENT: 'Create a new password you have not used before',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
  OTP_ALREADY_VERIFIED: 'OTP already verified',
  INVALID_OTP_TYPE: 'OTP type mismatch. Please use the correct flow',
  AUTH_HEADER_MISSING: 'Authorization header missing or malformed',
  INVALID_TOKEN: 'Invalid or expired token',
  INVALID_REFRESH_TOKEN: 'Invalid or expired refresh token',
  REFRESH_TOKEN_SUCCESS: 'Token refreshed successfully',
  TOO_MANY_OTP_REQUESTS: 'Too many OTP requests. Please try again later',
  TOO_MANY_VERIFY_OTP_ATTEMPTS: 'Too many verify OTP attempts. Please try again later',
  INVALID_SESSION: 'Invalid session',
  INVALID_FACEBOOK_TOKEN: 'Invalid Facebook token',
  FACEBOOK_USER_NOT_VERIFIED: 'Unable to verify Facebook user',
  FACEBOOK_VERIFICATION_FAILED: 'Facebook verification failed',
};