export const AUTH_MESSAGES = {
  EMAIL_OR_PHONE_REQUIRED: 'Please enter email or phone number.',
  INVALID_OTP: 'Incorrect code. Please try again.',
  OTP_SESSION_EXPIRED: 'Code expired. Please request a new one.',
  OTP_NOT_VERIFIED: 'Please verify the code before proceeding.',
  OTP_SENT: 'OTP sent successfully',
  OTP_VERIFIED: 'OTP verified successfully',
  OTP_ALREADY_VERIFIED: 'OTP already verified',
  TOO_MANY_OTP_REQUESTS: 'Please wait before requesting a new code.',
  TOO_MANY_VERIFY_OTP_ATTEMPTS: 'Maximum attempts reached. Please request a new code.',
  SMS_OTP_SEND_FAILED: 'Unable to send code. Please try again.',
  PASSWORD_CREATED: 'Password created successfully.',
  PASSWORD_ALREADY_SET: 'Password already set.',
  PASSWORD_NOT_SET: 'Please create your password first.',
  PASSWORD_DOES_NOT_MEET_CRITERIA: 'Password does not meet required criteria.',
  PASSWORD_MUST_BE_DIFFERENT: 'Create a new password you have not used before',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
  USERNAME_SET_SUCCESS: 'Username set successfully',
  USERNAME_TAKEN: 'Username is already taken',
  USERNAME_ALREADY_SET: 'Username already set.',
  USERNAME_NOT_SET: 'Please set your username first.',
  USERNAME_INVALID_FORMAT: 'Invalid Format.',
  USERNAME_DOT_POSITION: 'Username cannot start or end with a dot.',
  PROFILE_CREATED: 'Profile created successfully',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logged out successfully',
  INVALID_CREDENTIALS: 'Invalid email/username or password.',
  SESSION_EXPIRED: 'Session expired. Please login again.',
  USER_ALREADY_EXISTS: 'User already exists with this email or phone.',
  USER_NOT_FOUND: 'User not found',
  INVALID_OTP_TYPE: 'Invalid request. Please follow the correct flow.',
  AUTH_HEADER_MISSING: 'Authorization header missing or invalid.',
  INVALID_TOKEN: 'Invalid or expired token.',
  INVALID_REFRESH_TOKEN: 'Invalid or expired refresh token.',
  REFRESH_TOKEN_SUCCESS: 'Token refreshed successfully.',
  INVALID_SESSION: 'Invalid session. Please login again.',
  INVALID_FACEBOOK_TOKEN: 'Invalid Facebook token.',
  FACEBOOK_USER_NOT_VERIFIED: 'Unable to verify Facebook user.',
  FACEBOOK_VERIFICATION_FAILED: 'Unable to login with Facebook. Please try again.',
  GOOGLE_USER_NOT_VERIFIED: 'Unable to verify Google user.',
  GOOGLE_VERIFICATION_FAILED: 'Unable to login with Google. Please try again.',
  GOOGLE_EMAIL_NOT_VERIFIED: 'Google email is not verified.',
  APPLE_USER_NOT_VERIFIED: 'Unable to verify Apple user.',
  APPLE_VERIFICATION_FAILED: 'Unable to login with Apple. Please try again.',
  USE_SOCIAL_LOGIN: 'Password not set. Please login using social account or reset your password.',
  USER_UNDERAGE: 'You must be at least 18 years old to register.',
  INVALID_PHONE_NUMBER: 'Please enter a valid phone number.',
  COUNTRY_CODE_REQUIRED: 'Country code is required when phone is provided.',
  INVALID_COUNTRY_CODE: 'Please enter a valid country code.',
  PROVIDE_EMAIL_OR_PHONE: 'Provide either email or phone.',
  PROVIDE_EMAIL_OR_USERNAME: 'Either email or username is required',
};